version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-net

  app:
    build: .
    container_name: ecommerce-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - ecommerce-net
    command: sh -c "npm install && node app.js"

networks:
  ecommerce-net:
    driver: bridge
